import './debounce.test.js'
import './html-marker.test.js'
import './http-fetch.test.js'
import './i18n.test.js'
import './observable.test.js'
import './roles.test.js'
import './router.test.js'
import './util.test.js'
